name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-pytest:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Install Python dependencies
        run: pip install -U pip pytest

      - name: Install Codescanner
        run: pip install .

      - name: Run pytest
        run: pytest
